
import { refreshPage } from "./actions";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { connectDB } from "./services";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectDB();
  await refreshPage();
  return (
    <html lang="en">
      <body >
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
